id: PD354F05D
initial_creation_type: ocr
source_metadata:
  volumes:
    82b5010af1c441acb94374933d064c72:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: འཕགས་པ་ས་བཅུ་པའི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      volume_number: 65
